sonar.projectKey=AriaTechShop-ERP
sonar.projectName=AriaTechShop-ERP
sonar.sources=server
sonar.inclusions=server/app/Http/Controllers/InventoryController.php,server/app/Models/Inventory.php,server/database/migrations/2026_03_10_224311_add_min_stock_to_inventories_table.php,server/resources/views/inventory/create.blade.php,server/resources/views/inventory/edit.blade.php,server/resources/views/inventory/index.blade.php,server/routes/web.php
sonar.host.url=http://localhost:9000