name: Laravel CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4" # O la que uses en Fedora
          extensions: mbstring, dom, curl, libxml, mysql, pgsql

      - name: Install Dependencies
        run: |
          cd server
          composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Check PSR-4 Autoload (The "Anti-Pendejos" Check)
        run: |
          cd server
          composer dump-autoload -o
          # Si alguien puso una mayúscula mal, esto fallará en el CI de GitHub
